binop_separator = "Front"  # def
brace_style = "AlwaysNextLine"
combine_control_expr = true  # def
condense_wildcard_suffixes = false
control_brace_style = "AlwaysSameLine"  # def
disable_all_formatting = false  # def
empty_item_single_line = true  # def
enum_discrim_align_threshold = 80
fn_params_layout = "Tall"  # def
fn_single_line = false  # def
force_explicit_abi = true  # def
force_multiline_blocks = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 80
format_macro_matchers = true
format_macro_bodies = true
format_strings = false  # def
hard_tabs = true
hex_literal_case = "Lower"
imports_indent = "Block"  # def
imports_layout = "HorizontalVertical"
indent_style = "Block"  # def
inline_attribute_width = 0  # def
match_arm_blocks = false
match_arm_leading_pipes = "Never"  # def
match_block_trailing_comma = true
max_width = 80
merge_derives = true  # def
imports_granularity = "Preserve"  # def
newline_style = "Unix"
normalize_comments = false
normalize_doc_attributes = true
overflow_delimited_expr = true
remove_nested_parens = true  # def
reorder_impl_items = true
reorder_imports = true  # def
group_imports = "StdExternalCrate"
reorder_modules = true  # def
short_array_element_width_threshold = 0
space_after_colon = true  # def
space_before_colon = false  # def
spaces_around_ranges = false  # def
struct_field_align_threshold = 80
struct_lit_width = 0
struct_variant_width = 0
tab_spaces = 8
trailing_comma = "Vertical"  # def
trailing_semicolon = true  # def
type_punctuation_density = "Wide"  # def
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Off"
use_try_shorthand = true
wrap_comments = true
